version: "3"

services:
    nextcloud:
        image: lscr.io/linuxserver/nextcloud:latest
        container_name: nextcloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            # Optional environment variables
            # - NEXTCLOUD_ADMIN_USER=admin
            # - NEXTCLOUD_ADMIN_PASSWORD=admin_password
            # - MYSQL_HOST=nextcloud-db
            # - MYSQL_DATABASE=nextcloud
            # - MYSQL_USER=nextcloud
            # - MYSQL_PASSWORD=nextcloud_db_password
        volumes:
            - nextcloud_config_vol:/config
            - /nextcloud_vol:/data:z
        # ports:
        #     - 8080:80
        # depends_on:
        #     - nextcloud-db
        restart: unless-stopped
        networks:
            - traefik_net
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.hq.adhadse.com`)"
            - "traefik.http.routers.nextcloud.entrypoints=websecure"
            - "traefik.http.routers.nextcloud.tls=true"
            - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
            - "traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN"
            - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"
            - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
            - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
            - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

networks:
    traefik_net:
        external: true

volumes:
    nextcloud_config_vol:
        external: true
