version: "3.9"

services:
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        # ports:
        #     - "8888:80"
        dns:
            - 192.168.1.1
        networks:
            - traefik_net
        # secrets:
        #     - PGADMIN_PASSWORD
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/var/lib/pgadmin
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_net
            - traefik.http.routers.pgadmin.rule=Host(`pgadmin.hq.adhadse.com`)
            - traefik.http.routers.pgadmin.entrypoints=websecure
            - traefik.http.routers.pgadmin.tls=true
            - traefik.http.routers.pgadmin.tls.certresolver=production
            - traefik.http.routers.pgadmin.service=pgadmin
            - traefik.http.services.pgadmin.loadbalancer.server.port=80

networks:
    traefik_net:
        external: true

volumes:
    pgadmin:
