version: '3'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    # ports:
    #   - 3000:3001/tcp
    volumes:
      - uptime_kuma_vol:/app/data
    restart: always
    labels:
      # WebUI
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.uptime-kuma.rule=Host(`uptimekuma.hq.adhadse.com`)
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=production
      - traefik.http.routers.uptime-kuma.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

      # New router for status.hq.adhadse.com
      - traefik.http.routers.status-kuma.rule=Host(`status.hq.adhadse.com`)
      - traefik.http.routers.status-kuma.entrypoints=websecure
      - traefik.http.routers.status-kuma.tls=true
      - traefik.http.routers.status-kuma.tls.certresolver=production
      - traefik.http.routers.status-kuma.service=status-kuma
      - traefik.http.services.status-kuma.loadbalancer.server.port=3001

      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Host=status.hq.adhadse.com
      - traefik.http.routers.uptime-kuma.middlewares=sslheader
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    resources:
      limits:
        cpus: '0.001'
        memory: 200M

volumes:
  uptime_kuma_vol:

networks:
  traefik_net:
    external: true
